version = 0.1

[default.global.parameters]

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "sam/localstack"
region = "us-east-1"
disable_rollback = true

